#!/bin/bash

log() {
	echo "$(date +"%Y-%m-%d %H:%M:%S") [$$] $@"
}

if ! set | grep '^error ()' >/dev/null; then
	error() {
		log "Обнаружена ошибка в тесте $0"
	}
fi


if ! set | grep '^fix ()' >/dev/null; then
	fix() {
		return 1
	}
fi

if ! set | grep '^fix_ok ()' >/dev/null; then
	fix_ok() {
		log "Исправление удалось"
	}
fi

drhouse_main_nosafemode() {
	check && exit 0 || error
	fix && fix_ok || exit 1
	check && exit 0 || exit 2
}

drhouse_main() {
	check && exit 0 || error
	fix && fix_ok || exit 254
	check && exit 0 || exit 254
}

if [ $# = 1 ] && fgrep -q "$1() {" "$BASH_SOURCE"; then
	"$1"
fi
